import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourceSchemaPath = resolve(projectRoot, 'prisma/schema.prisma')
const prismaCliPath = resolve(projectRoot, 'node_modules/prisma/build/index.js')
const supportedProviders = ['sqlite', 'postgresql']

function readProvider() {
  const provider = (process.env.DATABASE_PROVIDER || 'sqlite').trim().toLowerCase()

  if (!supportedProviders.includes(provider)) {
    throw new Error(
      `Unsupported DATABASE_PROVIDER "${provider}". Use "sqlite" or "postgresql".`
    )
  }

  return provider
}

function schemaPath(provider) {
  return resolve(projectRoot, `prisma/generated/${provider}/schema.prisma`)
}

function createSchema(source, provider) {
  const generatorPattern = /generator client \{[^}]*\}/
  const datasourcePattern = /datasource db \{[^}]*\}/

  if (!generatorPattern.test(source) || !datasourcePattern.test(source)) {
    throw new Error('Unable to find the Prisma generator or datasource block.')
  }

  const generatorBlock = `generator client {
  provider     = "prisma-client"
  output       = "../../../server/generated/prisma/${provider}"
  moduleFormat = "esm"
}`
  const datasourceBlock = `datasource db {
  provider = "${provider}"
}`
  const withGenerator = source.replace(generatorPattern, generatorBlock)
  const generatedSchema = withGenerator.replace(datasourcePattern, datasourceBlock)

  return `// Generated by scripts/prisma.mjs. Do not edit.\n\n${generatedSchema}`
}

function prepareSchemas() {
  const source = readFileSync(sourceSchemaPath, 'utf8')

  for (const provider of supportedProviders) {
    const targetPath = schemaPath(provider)
    mkdirSync(dirname(targetPath), { recursive: true })
    writeFileSync(targetPath, createSchema(source, provider))
  }
}

function validateDatabaseUrl(provider) {
  const url = process.env.DATABASE_URL || ''

  if (provider === 'sqlite') {
    if (url && !url.startsWith('file:')) {
      throw new Error('SQLite DATABASE_URL must start with "file:".')
    }
    return
  }

  if (!url) {
    throw new Error('DATABASE_URL is required when DATABASE_PROVIDER is "postgresql".')
  }

  if (!url.startsWith('postgresql://') && !url.startsWith('postgres://')) {
    throw new Error('PostgreSQL DATABASE_URL must start with "postgresql://" or "postgres://".')
  }
}

function runPrisma(args, provider, generateOnly = false) {
  const databaseUrl = generateOnly
    ? provider === 'sqlite'
      ? 'file:./.data/micromatrix-email-manager.sqlite'
      : 'postgresql://prisma:prisma@127.0.0.1:5432/prisma'
    : process.env.DATABASE_URL
  const result = spawnSync(
    process.execPath,
    [prismaCliPath, ...args, '--schema', schemaPath(provider)],
    {
      cwd: projectRoot,
      env: {
        ...process.env,
        DATABASE_PROVIDER: provider,
        ...(databaseUrl ? { DATABASE_URL: databaseUrl } : {})
      },
      stdio: 'inherit'
    }
  )

  if (result.error) {
    throw result.error
  }

  if (result.status !== 0) {
    process.exit(result.status ?? 1)
  }
}

const args = process.argv.slice(2)

if (args.length === 0) {
  throw new Error('Missing Prisma command.')
}

prepareSchemas()

if (args[0] === 'generate') {
  for (const provider of supportedProviders) {
    runPrisma(['generate'], provider, true)
  }
} else {
  const provider = readProvider()
  validateDatabaseUrl(provider)
  runPrisma(args, provider)
}
